from pydantic import BaseModel, Field



class UserQuery(BaseModel):
    """
    Model to represent the user query.
    """
    query: str = Field(..., description="The query string provided by the user.")

class AgentResponse(BaseModel):
    """
    Model to represent the response from the agent.
    """
    response: str = Field(..., description="The response generated by the agent.")
